[project]
name = "CFGpy"
version = "1.0.0" 
description = "A python package for handling Creative Foraging Game behavioral data and numerical simulations"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3,
    "pycognito,
    "appdirs",
    "numpy",
    "pandas",
    "requests",
    "tqdm",
    "networkx",
    "matplotlib",
    "seaborn",
    "scipy",
    "dacite",
    "PyYAML",
    # Based on our previous discussion, adding this ensures pkg_resources works
    "setuptools",
]

[project.urls]
Homepage = "https://github.com/ComDePri/CFGpy"

[project.scripts]
run_cfg_pipeline = "CFGpy.behavioral.Pipeline:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["CFGpy"]