# parsed data format
PARSED_PLAYER_ID_KEY = 'id'
PARSED_TIME_KEY = 'absolute start time'
PARSED_ALL_SHAPES_KEY = 'actions'
SHAPE_ID_IDX = 0
SHAPE_MOVE_TIME_IDX = 1
SHAPE_SAVE_TIME_IDX = 2
PARSED_CHOSEN_SHAPES_KEY = 'chosen_shapes'

# preprocessing
MIN_SAVE_FOR_EXPLOIT = 3
EXPLORE_KEY = "explore"
EXPLOIT_KEY = "exploit"

# measure calculation
FIRST_SHAPE_ID = 1
MEASURES_ID_KEY = "ID"
MEASURES_START_TIME_KEY = "Date/Time"
N_MOVES_KEY = "Total # moves"
N_GALLERIES_KEY = "#galleries"
N_CLUSTERS_KEY = "#clusters"
EXPLORE_EFFICIENCY_KEY = "exp efficiency"
EXPLOIT_EFFICIENCY_KEY = "scav efficiency"
GAME_DURATION_KEY = "Total Play Time"
MEDIAN_EXPLORE_LENGTH_KEY = "median exp steps"
MEDIAN_EXPLOIT_LENGTH_KEY = "median scav steps"
LONGEST_PAUSE_KEY = "max dt"
DEFAULT_FINAL_OUTPUT_FILENAME = "CFG measures.csv"
MIN_OVERLAP_FOR_SEMANTIC_CONNECTION = 2

# default soft filters
MANUALLY_EXCLUDED_IDS = ()
MIN_N_MOVES = 80
MIN_N_CLUSTERS = 1
MIN_GAME_DURATION_SEC = 600
MAX_PAUSE_DURATION_SEC = 90
MAX_ZSCORE_FOR_OUTLIERS = 3
